<?php
session_start();

require_once "inc/classes/chatgroup.inc.php";
require_once "inc/classes/database.inc.php";
require_once "inc/classes/invitation.inc.php";
require_once "inc/classes/message.inc.php";
require_once "inc/classes/user.inc.php";
require_once "inc/classes/database.inc.php";
$database = new Database();

if (isset($_SESSION["username"])) {
    $result = $database->getUser($_SESSION["username"]);
    $user = new User($result["idu"], $result["nickname"], $result["authority"]);
}
if (isset($_GET["id"])) {
    $_SESSION["idc"] = $_GET["id"];
    $chatgroup = new Chatgroup($_SESSION["idc"], "chatgroup");
}
?>