<?php
if (isset($_SESSION["errorMessage"])) {
    ?>
    <div class="errorMessage">
        <?= $_SESSION["errorMessage"] ?>
    </div>
    <?php
}
?>
<div class="chat">
    <?php
    if (isset($_SESSION["username"])) {
        $user->loadInvitations($database);
        $user->displayInvitations();
    } else {
        echo "You are not logged in";
    }
    ?>
</div>
<?php
    if (isset($_SESSION["username"])) {
?>
<section id="chat_groups">
    <div class=" navbar navbar-expand-lg navigation">
        <div class="container-fluid">
            <div class="offcanvas offcanvas-start" tabindex="-1"  id="offcanvasNavbar"
                 aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-body offcanvasgroups justify-content-center">
                    <ul class="navbar-nav justify-content-start ">
                        <div class="burger" >  
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle createChatGroups" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                    new chat
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                    <form action='#' method='post' class="send_chat">
                                        <input type='text' name='uid' class='text tx dropdown-item' placeholder='Username' required>
                                        <input type='text' name='message' class='text tx dropdown-item' placeholder='Message'>
                                        <input type='submit' name='sendChatInvitation' class='btn btn-secondary submit sub dropdown-item' value='Send'>
                                    </form>
                                </ul>
                            </div>
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle createChatGroups" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                                    new group
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
                                    <form action='#' method='post' class="send_chat">
                                        <input type='text' name='name' class='text tx dropdown-item' placeholder='Group name' required>
                                        <input type='submit' name='createGroup' class='btn btn-secondary submit sub dropdown-item' value='Create'>
                                    </form>
                                </ul>
                            </div>   
                            <p style="text-align: center;">
                                <?php
                                    $user->loadChatGroups($database);
                                    $user->displayChatGroups($database);
                                ?>
                            </p>
                        </div>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="chat">
        <?php
            if (isset($_GET["id"])) {
                if (!$chatgroup->isDirectChat()) {
        ?>
        <div class="dropdown" style="position: absolute; top: 2%; right: 1%;">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton3" data-bs-toggle="dropdown" aria-expanded="false">
                +
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton3">
                <form action='#' method='post' class="send_chat">
                    <input type='text' name='uid' class='text tx dropdown-item' placeholder='Username' required>
                    <input type='text' name='message' class='text tx dropdown-item' placeholder='Message'>
                    <input type='submit' name='sendGroupInvitation' class='btn btn-secondary submit sub dropdown-item' value='Send'>
                </form>
            </ul>
        </div>
        <div class="chat" style="flex-grow:1;">
            <div style="height: 500px; overflow:auto">
                <?php 
                    $chatgroup->loadMessages($database);
                    $chatgroup->printMessages();
                ?>
            </div>
            <form action="#" method="post" class="send_chat" style="padding-top: 20px;">
                <input type="text" name="message" placeholder="Aa" class="message tx">
                <input type="submit" name="sendMessage" value="Send" class="sendMessage sub btn btn-secondary">
            </form>
        </div>
        <?php
                }
            } 
            else {
                echo "<p style='text-align:center;'>Please select chatgroup</p>";
            }
        ?>
    </div>
</section>
<?php
    }
?>