<?php   
    if(isset($errorMessage)) {
?>
<div class="errorMessage">
    <?= $errorMessage ?>
</div>
<?php
    }
?>
<div class="chat">
    <?php
    if (isset($_SESSION["username"])) {
        $user->loadInvitations($database);
        $user->displayInvitations();
    }
    else {
        echo "You are not logged in";
    }
    ?>
</div>
<?php
    if (isset($_SESSION["username"])) {
?>
<section id="chat_groups">
    <div class=" navbar navbar-expand-lg navigation">
        <div class="container-fluid">
            <div class="offcanvas offcanvas-start" tabindex="-1"  id="offcanvasNavbar"
                 aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-body offcanvasgroups justify-content-center">
                    <ul class="navbar-nav justify-content-start ">
                        <div class="burger" >
                            <form action='#' method='post' class="send_chat">
                                <input type='text' name='uid' class='text tx' placeholder='Send chat request...'>
                                <input type='submit' name='sendInvitation' class='submit sub' value='Send'>
                            </form>
                            <p style="text-align: center;">
                                <?php
                                    echo "Hi " . $_SESSION["username"] . ".<br>";
                                    //print_r($result);
                                    $user->loadChatGroups($database);
                                    $user->displayChatGroups($database);
                                ?>
                            </p>
                        </div>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="chat">
    <?php
        if (isset($_GET["id"])) {
    ?>
    <div class="chat" style="flex-grow:1;">
        <div>
            <?php 
                $chatgroup->loadMessages($database);
                $chatgroup->printMessages();
            ?>
        </div>
        <form action="#" method="post" class="send_chat" style="padding-top: 20px;">
            <input type="text" name="message" placeholder="Aa" class="message tx">
            <input type="submit" name="sendMessage" value="Send" class="sendMessage sub">
        </form>
    </div>
    <?php
        } 
        else {
            
            echo "<p style='text-align:center;'>Please select chatgroup</p>";
        }
    ?>
    </div>  
</section>

<?php
    }
?>