<div class="log_sig">
    <h1 class="login-title">Log In</h1>
    <form action="#" method="post">
        <?php   
            if(isset($errorMessage)) {
        ?>
        <div class="errorMessage">
            <?= $errorMessage ?>
        </div>
        <?php
            }
        ?>
        <div class="input">
            <input class="input__field_2" name="uid" type="text" id="name" required />
            <label for="name" class="input__label">Username</label>
            <br>
        </div>
        <div class="input">
            <input class="input__field" name="pwd" type="password" id="password" required />
            <label for="password" class="input__label">Password</label>
            <span class="input__icon-wrapper">
                <i class="input__icon ri-eye-off-line"></i>
            </span>         
        </div>
        <br>
        <input type="submit" name="submit" class="login-button" value="Log In">
    </form>
</div>
<script>
    const inputIcon = document.querySelector('.input__icon')
    const inputPassword = document.querySelector('.input__field')

    inputIcon.addEventListener('click', () => {
        inputIcon.classList.toggle('ri-eye-off-line')
        inputIcon.classList.toggle('ri-eye-line')
        inputPassword.type =
        inputPassword.type === 'password' ? 'text' : 'password'
    })
</script>