<div class="log_sig">
    <h1 class="login-title">Create account</h1>
    <form action="#" method = "post">
    <?php   
            if(isset($_SESSION["errorMessage"])) {
        ?>
        <div class="errorMessage">
            <?= $_SESSION["errorMessage"] ?>
        </div>
        <?php
            }
        ?>
        <div class="input">
            <input class="input__field_2" name="uid" type="text" id="username" required />
            <label for="username" class="input__label">Username</label>
            <br>
        </div>
        <div class="input">
            <input class="input__field" name="pwd" type="password" id="pwd1" required />
            <label for="pwd1" class="input__label">Password</label>
            <br>
        </div>
        <div class="input"> 
            <input class="input__field" name="pwd2" type="password" id="pwd2" required />
            <label for="pwd2" class="input__label">Repeat password</label>     
        </div>
        <br>
        <input type="submit" name="submit" class="login-button" value="Create Account">
    </form>
</div>