<div class="log_sig">
    <h1 class="login-title">Create account</h1>
    <form action="#" method = "post">
    <?php   
            if(isset($errorMessage)) {
        ?>
        <div class="errorMessage">
            <?= $errorMessage ?>
        </div>
        <?php
            }
        ?>
        <div class="input">
            <input class="input__field_2" name="uid" type="text" required />
            <label for="username" class="input__label">Username</label>
            <br>
        </div>
        <div class="input">
            <input class="input__field" name="pwd" type="password"  required />
            <label for="password" class="input__label">Password</label>
            <br>
        </div>
        <div class="input"> 
            <input class="input__field" name="pwd2" type="password"  required />
            <label for="password" class="input__label">Repeat password</label>     
        </div>
        <br>
        <input type="submit" name="submit" class="login-button" value="Create Account">
    </form>
</div>